version: "3.7"
services:
  rancher:
    image: rancher/rancher:v2.3.3
    volumes: 
      - ./rancher:/var/lib/rancher
    expose:
      - 80
    # ports:
    #   - 80:80
    environment:
      - VIRTUAL_HOST=rancher-01.jitrak.com
      - LETSENCRYPT_HOST=rancher-01.jitrak.com
      - LETSENCRYPT_EMAIL=paripol.toopiroh@gmail.com
    restart: unless-stopped
networks:
  default:
    external:
      name: nginx-proxy